server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

    url: jdbc:mysql://192.168.226.10:3306/aoplog?serverTimezone=UTC




